export const content = {
  ar: {
    brand: {
      name: "الصناعة الإبداعية",
      short: "CI",
    },
    nav: {
      about: "من ",
      services: "خدماتنا",
      products: "منتجاتنا",
      vision: "رؤيتنا",
      goals: "أهدافنا",
      clients: "عملاؤنا",
      contact: "تواصل معنا",
      cta: "تواصل معنا",
    },
    actions: {
      language: "تبديل اللغة",
      theme: "تبديل المظهر",
      dark: "الوضع الداكن",
      light: "الوضع الفاتح",
      toEnglish: "English",
      toArabic: "عربي",
    },
    hero: {
      tag: "🏭 صناعة عمانية إبداعية لا لها",
      titleMain: "الصناعة",
      titleHighlight: "الإبداعية",
      subtitle:
        "مصنع عمان في توفير خطوط الإنتاج الصناعية والمنتجات البلاستيكية بأعلى معايير الجودة العالمية",
      primary: "اكتشف منتجاتنا",
      secondary: "تواصل معنا",
      scroll: "مرر",
    },
    about: {
      tag: "من نحن",
      titleMain: "شركة",
      titleHighlight: "عمانية",
      titleRest: "بكوادر متميزة",
      desc: "الصناعة الإبداعية شركة بإدارة عمانية وكادر مميز من مهندسين عمانيين ذوي خبرة أكثر من عشر سنوات. جاءت فكرة الشركة لتلائم الخطط الاستراتيجية الصناعية في السلطنة، لتساهم في وصولها إلى مصاف الدول المتقدمة وتحفّز التقدم في الصناعات التحويلية الوطنية. نحن مصنع مختص في توفير خطوط الإنتاج الصناعية مع توفير المنتجات البلاستيكية للعلامات التجارية، ونساهم في تحقيق أهداف التنمية الاقتصادية عبر تلبية احتياجات السوق المحلي والمصانع الوطنية مع السعي للتوسع إقليميًا وعالميًا.",
      stats: [
        { value: "+10", label: "سنوات خبرة" },
        { value: "100%", label: "كوادر عمانية" },
        { value: "🏆", label: "معايير عالمية" },
      ],
      features: [
        {
          icon: "🏭",
          title: "معايير عالمية",
          text: "وحدات صناعية وفق أحدث المواصفات",
        },
        {
          icon: "⚙️",
          title: "تقنيات متطورة",
          text: "ابتكار صناعي وتقنية معلومات",
        },
        {
          icon: "🛡️",
          title: "صحة وسلامة",
          text: "بيئة عمل آمنة ومعتمدة",
        },
        {
          icon: "🌍",
          title: "انتشار عالمي",
          text: "أسواق محلية وإقليمية ودولية",
        },
      ],
    },
    products: {
      tag: "منتجاتنا",
      titleMain: "حلول",
      titleHighlight: "التغليف",
      desc: "منتجات صناعية عالية الجودة لتثبيت وربط وتغليف الشحنات بكفاءة.",
      items: [
        { slug: "pp-strap", name: "PP strap" },
        { slug: "ring-holder", name: "Ring holder" },
        { slug: "core-plug", name: "Core plug" },
        { slug: "pp-strap-clip", name: "مشبك ربط شريط PP" },
      ],
    },
    services: {
      tag: "خدماتنا",
      titleMain: "خدمات",
      titleHighlight: "التصنيع",
      desc: "نقدّم خدمات التصنيع والصناعة البلاستيكية للعلامات التجارية والمصانع.",
      items: [
        {
          num: "01",
          icon: "🏭",
          title: "التصنيع",
          text: "حلول تصنيع صناعية وتوفير خطوط الإنتاج.",
        },
        {
          num: "02",
          icon: "🧴",
          title: "الصناعة البلاستيكية",
          text: "مثل الأغطية والعلب ومواد التغليف.",
        },
      ],
    },
    vision: {
      cards: [
        {
          icon: "🎯",
          label: "رؤيتنا",
          title: "تكوين مجموعة شركات صناعية متكاملة",
          text: "ناجحة اقتصادياً، متقدمة علمياً وإدارياً وصناعياً، لخدمة المجتمع والمساهمة في التنمية المستدامة.",
        },
        {
          icon: "📜",
          label: "رسالتنا",
          title: "حلول صناعية احترافية",
          text: "تقديم حلول صناعية احترافية تسهّل الأداء على المصانع وعلى العلامات التجارية، بأحدث التقنيات وأعلى معايير الجودة.",
        },
      ],
    },
    goals: {
      tag: "أهدافنا",
      titleMain: "نسعى لتحقيق",
      titleHighlight: "التميز",
      items: [
        "نساهم في زرع الثقة في المنتج العماني ومنحه المجال للمنافسة في الأسواق العالمية",
        "المساهمة في التحول بوتيرة أسرع نحو الثورة الصناعية الرابعة في السلطنة",
        "المساهمة في وصول السلطنة إلى مصاف الدول المتقدمة وتحفيز التقدم في الصناعات التحويلية",
        "بناء وتطوير المصانع بأحدث التقنيات وبأعلى معايير الجودة العالمية",
        "تطوير المنتجات البلاستيكية وتصميمها باستخدام أفضل التقنيات الصناعية",
        "تقديم الاستشارات الصناعية التي تسهم في تطوير المجال الصناعي في السلطنة",
      ],
    },
    why: {
      tag: "لماذا نحن؟",
      titleMain: "ما يميز",
      titleHighlight: "الصناعة الإبداعية",
      items: [
        {
          icon: "🇴🇲",
          title: "كوادر عمانية متخصصة",
          text: "فريق عمل عماني متكامل ذو خبرة ومدرب على تنفيذ الأعمال في أقرب وقت ممكن",
        },
        {
          icon: "⚡",
          title: "تنفيذ سريع ودقيق",
          text: "معدات عالية الدقة والأمان قابلة للتطوير في أي لحظة دون البدء من جديد",
        },
        {
          icon: "🌱",
          title: "دعم التنمية المستدامة",
          text: "نساهم في تحقيق أهداف التنمية الاقتصادية بالسلطنة ورفع الميزان التجاري العماني",
        },
      ],
    },
    clients: {
      tag: "عملاؤنا",
      titleMain: "شركاء",
      titleHighlight: "النجاح",
      images: [
        "شريك نجاح 1",
        "شريك نجاح 2",
        "شريك نجاح 3",
        "شريك نجاح 4",
        "شريك نجاح 5",
        "شريك نجاح 6",
        "شريك نجاح 7",
      ],
    },
    contact: {
      tag: "تواصل معنا",
      titleMain: "هل لديك مشروع",
      titleHighlight: "في ذهنك؟",
      desc: "نحن هنا لتحويل أفكارك الصناعية إلى واقع ملموس بأعلى معايير الجودة",
      details: [
        { icon: "📍", text: "سلطنة عُمان / مسقط" },
        {
          icon: "📞",
          text: "+968 9513 6368",
          dir: "ltr",
          actions: [
            { type: "call", href: "tel:+96895136368" },
            { type: "whatsapp", href: "https://wa.me/96895136368" },
          ],
        },
        {
          icon: "✉️",
          text: "info@creativesindustry.com",
          href: "mailto:info@creativesindustry.com",
        },
      ],
      form: {
        name: "الاسم الكامل",
        namePlaceholder: "أدخل اسمك",
        email: "البريد الإلكتروني",
        emailPlaceholder: "example@email.com",
        phone: "رقم الهاتف",
        phonePlaceholder: "+968 XXXX XXXX",
        message: "رسالتك",
        messagePlaceholder: "اكتب رسالتك هنا...",
        submit: "إرسال الرسالة ✦",
        sending: "جاري الإرسال...",
        success: "تم إرسال الرسالة بنجاح.",
        error: "حدث خطأ، حاول مرة أخرى.",
        required: "هذا الحقل مطلوب.",
        invalidEmail: "يرجى إدخال بريد إلكتروني صحيح.",
        emailNotValid: "هذا البريد غير موجود أو غير مُفعل.",
        invalidPhone: "يرجى إدخال رقم هاتف صحيح.",
      },
    },
    footer: {
      copy: "© 2025 الصناعة الإبداعية — Creative Industry. جميع الحقوق محفوظة.",
      social: {
        facebook: "فيسبوك",
        linkedin: "لينكدإن",
        instagram: "إنستغرام",
        twitter: "تويتر",
      },
    },
  },
  en: {
    brand: {
      name: "Creative Industry",
      short: "CI",
    },
    nav: {
      about: "About Us",
      services: "Services",
      products: "Products",
      vision: "Vision",
      goals: "Goals",
      clients: "Clients",
      contact: "Contact",
      cta: "Contact Us",
    },
    actions: {
      language: "Switch language",
      theme: "Toggle theme",
      dark: "Dark mode",
      light: "Light mode",
      toEnglish: "English",
      toArabic: "Arabic",
    },
    hero: {
      tag: "🏭 Unique Omani creative manufacturing",
      titleMain: "Creatives",
      titleHighlight: "Industry",
      subtitle:
        "An Omani factory specialized in production lines and plastic products with the highest global quality standards",
      primary: "Explore Products",
      secondary: "Contact Us",
      scroll: "scroll",
    },
    about: {
      tag: "About",
      titleMain: "An",
      titleHighlight: "Omani",
      titleRest: "company with outstanding talent",
      desc: "Creative Industry is an Omani-managed company with a distinguished team of Omani engineers with over ten years of experience. The company was established to align with the Sultanate's industrial strategy, supporting its advancement and the growth of national manufacturing industries. We are a factory specialized in providing industrial production lines along with plastic products for brands, serving the local market and national factories while expanding regionally and globally.",
      stats: [
        { value: "+10", label: "Years Experience" },
        { value: "100%", label: "Omani Team" },
        { value: "🏆", label: "Global Standards" },
      ],
      features: [
        {
          icon: "🏭",
          title: "Global Standards",
          text: "Industrial units built to the latest specifications",
        },
        {
          icon: "⚙️",
          title: "Advanced Technology",
          text: "Industrial innovation and information technology",
        },
        {
          icon: "🛡️",
          title: "Health & Safety",
          text: "A certified, safe working environment",
        },
        {
          icon: "🌍",
          title: "Global Reach",
          text: "Local, regional, and international markets",
        },
      ],
    },
    products: {
      tag: "Products",
      titleMain: "Industrial",
      titleHighlight: "Products",
      desc: "High-quality industrial products for securing, strapping, and packing cargo.",
      items: [
        { slug: "pp-strap", name: "PP strap" },
        { slug: "ring-holder", name: "Ring holder" },
        { slug: "core-plug", name: "Core plug" },
        { slug: "pp-strap-clip", name: "PP Strap Clip" },
      ],
    },
    services: {
      tag: "Our Services",
      titleMain: "Industrial",
      titleHighlight: "Services",
      desc: "Manufacturing and plastic industry solutions for factories and brands.",
      items: [
        {
          num: "01",
          icon: "🏭",
          title: "Manufacturing",
          text: "Industrial manufacturing and production-line solutions.",
        },
        {
          num: "02",
          icon: "🧴",
          title: "Plastic Industry",
          text: "Such as covers, cans, and packaging materials.",
        },
      ],
    },
    vision: {
      cards: [
        {
          icon: "🎯",
          label: "Vision",
          title: "Building an integrated group of industrial companies",
          text: "Economically successful and scientifically, administratively, and industrially advanced—serving society and contributing to sustainable development.",
        },
        {
          icon: "📜",
          label: "Mission",
          title: "Professional industrial solutions",
          text: "Delivering professional industrial solutions that simplify operations for factories and brands with the latest technologies and highest quality standards.",
        },
      ],
    },
    goals: {
      tag: "Goals",
      titleMain: "We Strive for",
      titleHighlight: "Excellence",
      items: [
        "Building trust in Omani products and empowering them to compete globally",
        "Accelerating the transition toward the Fourth Industrial Revolution in the Sultanate",
        "Supporting Oman’s rise among advanced nations and driving progress in manufacturing industries",
        "Building and developing factories with the latest technologies and highest global quality standards",
        "Developing and designing plastic products using the best industrial technologies",
        "Providing industrial consulting that advances the sector in Oman",
      ],
    },
    why: {
      tag: "Why Us?",
      titleMain: "What Makes",
      titleHighlight: "Creative Industry",
      items: [
        {
          icon: "🇴🇲",
          title: "Specialized Omani Team",
          text: "A complete Omani team with experience, trained to deliver quickly",
        },
        {
          icon: "⚡",
          title: "Fast, Precise Execution",
          text: "High-precision, safe equipment that can be upgraded at any time without starting over",
        },
        {
          icon: "🌱",
          title: "Sustainable Development",
          text: "Contributing to economic development goals and improving Oman’s trade balance",
        },
      ],
    },
    clients: {
      tag: "Clients",
      titleMain: "Partners in",
      titleHighlight: "Success",
      images: [
        "Success partner 1",
        "Success partner 2",
        "Success partner 3",
        "Success partner 4",
        "Success partner 5",
        "Success partner 6",
        "Success partner 7",
      ],
    },
    contact: {
      tag: "Contact",
      titleMain: "Have a project",
      titleHighlight: "in mind?",
      desc: "We’re here to turn your industrial ideas into a tangible reality with top quality.",
      details: [
        { icon: "📍", text: "Oman / Muscat" },
        {
          icon: "📞",
          text: "+968 9513 6368",
          dir: "ltr",
          actions: [
            { type: "call", href: "tel:+96895136368" },
            { type: "whatsapp", href: "https://wa.me/96895136368" },
          ],
        },
        {
          icon: "✉️",
          text: "info@creativesindustry.com",
          href: "mailto:info@creativesindustry.com",
        },
      ],
      form: {
        name: "Full Name",
        namePlaceholder: "Enter your name",
        email: "Email",
        emailPlaceholder: "example@email.com",
        phone: "Phone",
        phonePlaceholder: "+968 XXXX XXXX",
        message: "Your Message",
        messagePlaceholder: "Write your message here...",
        submit: "Send Message ✦",
        sending: "Sending...",
        success: "Message sent successfully.",
        error: "Something went wrong. Please try again.",
        required: "This field is required.",
        invalidEmail: "Please enter a valid email.",
        emailNotValid: "This email does not exist or is not active.",
        invalidPhone: "Please enter a valid phone number.",
      },
    },
    footer: {
      copy: "© 2025 Creative Industry. All rights reserved.",
      social: {
        facebook: "Facebook",
        linkedin: "LinkedIn",
        instagram: "Instagram",
        twitter: "Twitter",
      },
    },
  },
};
